package rules

import org.folio.rest.jaxrs.model.LoanPolicy;
import org.folio.rest.jaxrs.model.Error;
import org.folio.rest.jaxrs.model.Parameter;

rule "Mixed objects Rule 4"

no-loop

when
  error : Error()
  m1 : LoanPolicy
      (
        eval(m1.getLoansPolicy().getProfileId().equalsIgnoreCase("Fixed"))
        && m1.getRenewable()  == true
        && m1.getRenewalsPolicy() != null
        && m1.getRenewalsPolicy().getDifferentPeriod() == true
        && m1.getRenewalsPolicy().getPeriod() != null
      )
then
  error.setMessage("Period in RenewalsPolicy is not allowed for policies with Fixed profile");
  Parameter param = new Parameter();
  param.setKey("period");
  param.setValue("" + m1.getRenewalsPolicy().getPeriod());
  java.util.List<Parameter> p = new java.util.ArrayList<>();
  p.add(param);
  error.setParameters(p);
  throw new java.lang.Exception("ProfileId = Fixed, but period is provided");
end
