#%RAML 1.0
title: Cancellation Reasons
version: v1.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Cancellation Reasons API
    content: <b>Storage for cancellation reasons</b>

types:
  cancellation-reason: !include cancellation-reason.json
  cancellation-reasons: !include cancellation-reasons.json
  errors: !include raml-util/schemas/errors.schema
  parameters: !include raml-util/schemas/parameters.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/cancellation-reason-storage:
  /cancellation-reasons:
    displayName: Cancellation Reasons
    type:
      collection:
        exampleCollection: !include examples/cancellation-reasons.json
        exampleItem: !include examples/cancellation-reason.json
        schemaCollection: cancellation-reasons
        schemaItem: cancellation-reason
    get:
      is: [
        validate,
        pageable,
        searchable: {description: "with valid searchable fields", example: "cancellationReason=lost"}
        ]
      responses:
        501:
          description: "Not implemented yet"
    post:
      is: [validate]
      responses:
        501:
          description: "Not implemented yet"
    delete:
      is: [language]
      responses:
        204:
          description: "All cancellation reasons deleted"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
        501:
          description: "Not implemented yet"
    /{cancellationReasonId}:
      type:
        collection-item:
          exampleItem: !include examples/cancellation-reason.json
          schema: cancellation-reason
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
