#%RAML 1.0
title: Checkout lock Storage
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Checkout lock API
    content: <b>Storage for checkout lock</b>

types:
  checkout-lock: !include checkout-lock.json
  checkout-locks: !include checkout-locks.json
  checkout-lock-request: !include checkout-lock-request.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml

/check-out-lock-storage:
  displayName: check out lock storage
  get:
    description: "Get Checkout Lock list"
    responses:
      200:
        description: "Return Checkout Lock List list"
        body:
          application/json:
            type: checkout-locks
      422:
        description: "Internal server error"
        body:
          text/plain:
  post:
    is: [validate]
    description: "creating a lock for the given userid"
    body:
      application/json:
        type: checkout-lock-request
        example: !include examples/checkout-lock-request.json
    responses:
      201:
        body:
          application/json:
            type: checkout-lock
            example: !include examples/checkout-lock.json
      400:
        description: "Bad Request"
        body:
          text/plain:
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
      503:
        description: "Failed to create lock for patron {userId}"
        body:
          text/plain:
            example: "Failed to create lock for patron "
  /{lockId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: checkout-lock
              example: !include examples/checkout-lock.json
          description: "Lock found for patron"
        400:
          description: "Bad Request"
          body:
            text/plain:
        404:
          description: "Failed to get lock for patron"
    delete:
      responses:
        204:
          description: "Lock is deleted"
        500:
          description: "Internal Server error"
          body:
            text/plain:
              example: "Internal server error"
