#%RAML 1.0
title: Circulation Rules Storage
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Circulation Rules Storage API
    content: <b>Storage for circulation rules</b>

types:
  circulation-rules: !include circulation-rules.json
  errors: !include raml-util/schemas/errors.schema
  parameters: !include raml-util/schemas/parameters.schema

traits:
  validate: !include raml-util/traits/validation.raml

/circulation-rules-storage:
  get:
    description: Get the circulation rules
    responses:
      200:
        body:
          application/json:
            type: circulation-rules
            example: !include examples/circulation-rules.json
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  put:
    description: Set the circulation rules
    body:
      application/json:
        type: circulation-rules
        example: !include examples/circulation-rules.json
    responses:
      204:
        description: "Circulation rules have been saved."
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
