#%RAML 1.0
title: Patron Notice Policies
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Patron Notice Policies API
    content: <b>Storage for Patron Notice Policies</b>

types:
  patron-notice-policy: !include patron-notice-policy.json
  errors: !include raml-util/schemas/errors.schema

/patron-notice-policy-storage:
  /patron-notice-policies:
    displayName: Patron Notice Policies
    post:
      description: "Create new Patron Notice Policy"
      body:
        application/json:
          type: patron-notice-policy
      responses:
        201:
          description: "Successfully created"
          body:
            application/json:
              type: patron-notice-policy
        422:
          description: "Unprocessable entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{patronNoticePolicyId}:
      put:
        description: "Update Patron Notice Policy by id"
        body:
          application/json:
            type: patron-notice-policy
        responses:
          204:
            description: "Successfully updated"
          404:
            description: "Not found"
            body:
              text/plain:
                example: "Not found"
          422:
            description: "Unprocessable entity"
            body:
              application/json:
                type: errors
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"

