#%RAML 1.0
title: Request Storage
version: v5.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9130

documentation:
  - title: Request Storage API
    content: <b>Storage for requests</b>

types:
  request: !include request.json
  requests: !include requests.json
  errors: !include raml-util/schemas/errors.schema
  parameters: !include raml-util/schemas/parameters.schema
  location: !include locations/location.json
  locations: !include locations/locations.json

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/request-storage:
  /requests:
    displayName: Requests
    type:
      collection:
        exampleCollection: !include examples/requests.json
        exampleItem: !include examples/request.json
        schemaCollection: requests
        schemaItem: request
    get:
      is: [pageable,
        searchable: {description: "by using CQL",
                        example: "requesterId=\"cf23adf0-61ba-4887-bf82-956c4aae2260\""}
        ]
      responses:
        501:
          description: "Not implemented yet"
    post:
      is: [validate]
      responses:
        501:
          description: "Not implemented yet"
    delete:
      responses:
        204:
          description: "All requests deleted"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
        501:
          description: "Not implemented yet"
    /{requestId}:
      type:
        collection-item:
          exampleItem: !include examples/request.json
          schema: request
      get:
        responses:
          501:
            description: "Not implemented yet"
      put:
        is: [validate]
        responses:
          501:
            description: "Not implemented yet"
      delete:
        responses:
          501:
            description: "Not implemented yet"
